#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'turtlebot3-example==2.1.2','console_scripts','turtlebot3_obstacle_detection'
__requires__ = 'turtlebot3-example==2.1.2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('turtlebot3-example==2.1.2', 'console_scripts', 'turtlebot3_obstacle_detection')()
    )
